# Números seudo aleatorios

Número aleatrorío entre o y 1

In [145]:
import random

In [146]:
# Obtener numero aleatorio entre 0 y 1
aleatorio_1 = random.random()

In [147]:
aleatorio_1

0.9548208159127507

## Numero aleatorio con los valores especificos

In [148]:
# Generar número aleatorio entre el 1 y el 100
aleatorio = random.randint(1,100)

In [153]:
aleatorio 

100

In [157]:
aleatorio_int = random.randint(1,6)

print(f'El número aleatorío es {aleatorio_int}') 

El número aleatorío es 5


# Crear matiz de números aleatorios

In [159]:
import numpy as np

In [167]:
# Primero se da el valor de los numeros aleatorios y segundo el tamaño de la matriz
matrix = np.random.randint(1,100, (4,4))

#Show matriz
print(matrix)

[[51 86  8 97]
 [59 78 85  6]
 [28 81 14 94]
 [68 53 78 88]]
